// src/ui/pwa.js
// Functions for Progressive Web App support.

/**
 * Build the list of URLs that should be precached by the service worker.
 * This runs at build time (imported by the Vite plugin) and also at runtime
 * when the UI needs the list. For simplicity we return a static list of the
 * core assets that are always present in the built site.
 */
export function buildPrecacheList() {
  // Paths are relative to the site root and prefixed with "./".
  return [
    "./index.html",
    "./manifest.webmanifest",
    "./icons/icon-192.png",
    "./icons/icon-512.png",
    "./icons/icon-maskable-192.png",
    "./icons/icon-maskable-512.png",
  ];
}

/**
 * Deterministic version identifier for the precache manifest.
 * The version must change when the manifest changes - we achieve that by
 * serialising the list. In a larger project you might hash the list.
 */
export const cacheVersion = JSON.stringify(buildPrecacheList());

/**
 * Register the service worker generated by the build step.
 * Called only in production.
 */
export function registerServiceWorker() {
  if (!('serviceWorker' in navigator)) return;
  navigator.serviceWorker.register('./sw.js').catch((err) => {
    console.error('Service worker registration failed:', err);
  });
}
